apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
    - image: codex4747/client
      context: client
      sync:
        manual:
        - src: src/**/*.js
          dest: .
      docker:
        dockerfile: Dockerfile
    - image: codex4747/comments
      context: comments
      sync:
        manual:
        - src: /*.js
          dest: .
      docker:
        dockerfile: Dockerfile
    - image: codex4747/event-bus
      context: event-bus
      sync:
        manual:
        - src: /*.js
          dest: .
      docker:
        dockerfile: Dockerfile
    - image: codex4747/moderation
      context: moderation
      sync:
        manual:
        - src: /*.js
          dest: .
      docker:
        dockerfile: Dockerfile
    - image: codex4747/query
      context: query
      sync:
        manual:
        - src: /*.js
          dest: .
      docker:
        dockerfile: Dockerfile
    - image: codex4747/posts
      context: posts
      sync:
        manual:
        - src: /*.js
          dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}